### ISSUE TITLE
cloning via ikvjwd.com not working

### ISSUE THREAD

**Issue by Mebus** [rcsheets/ikvjwd#2]
Hi!

Great service, but when I try to clone via the URL I get this error:

```
128 mebus@someserver ~ % git clone git@ikvjwd.com:atom/atom.git
Cloning into 'atom'...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
```

What's going wrong here?

Mebus

**Comment by f-andrey** [comment]
Yes, It seems worth pointing out that the anonymous working with github is not supported and must have an account to access the configured public key

**Comment by rcsheets** [comment]
I'll plan to add it to the AQ section of the home page.
